import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  statSync,
  writeFileSync,
} from 'node:fs'
import { homedir } from 'node:os'
import { basename, dirname, join, resolve } from 'node:path'
import type { RuncastleConfig, SessionKind, SessionRow } from '@runcastle/core'
import { sessionDir } from '@runcastle/core/paths'
import { RUNTIME_SPECS } from '../../doctor/doctor'
import { resolveTool } from '../../util/resolve-executable'
import { hookClientPath, renderSessionPrompt, serverUrlFor } from '../artifacts'
import { EDIT_TOOL_MATCHER, guardsEdits } from '../edit-guard'
import { resolvePluginDir } from '../skills-root'
import { kickoffLinesFor } from './skills'
import type {
  AgentRuntimeAdapter,
  RuntimeLaunchInput,
  RuntimeLaunchSpec,
  RuntimeReadiness,
} from './types'

/**
 * The Codex adapter (decision 9) — the same session, driven by the other CLI.
 *
 * Codex takes no per-launch configuration flags, so where the Claude adapter
 * passes `--settings`/`--mcp-config`/`--append-system-prompt-file` against the
 * human's real home, this one BUILDS a home: `<sessionDir>/codex-home`, handed
 * over as `CODEX_HOME`. Everything a session needs is a file in there —
 * `config.toml` (model, sandbox, approvals, project trust, the runcastle MCP
 * server), `hooks.json` (the same five lifecycle events invoking the same
 * runtime-neutral hook client), `AGENTS.md` (the per-kind system prompt) and a
 * copy of the human's own `auth.json`.
 *
 * That is the asymmetry decision 8 permits, and it is safe here for the reason
 * `CLAUDE_CONFIG_DIR` is not: Codex auth is one copyable file, and every
 * first-run and trust gate is bypassable through config we author ourselves.
 * Everything on the SERVER side — the hook routes, the edit guard, the MCP
 * server and its identity header — is untouched, because Codex's hook protocol
 * is Claude-shaped: the same stdin JSON, the same `hookSpecificOutput` verdicts.
 */

/** The CLI name, as `resolveTool` and the doctor's `codex` probe both spell it. */
const CODEX_BIN = 'codex'

/** The doctor probe that knows where this runtime installs and authenticates. */
const CODEX = RUNTIME_SPECS.codex

/** The synthetic per-session `CODEX_HOME` (decision 9): config, hooks, prompt, auth. */
export function codexHomeDir(sessionId: string): string {
  return join(sessionDir(sessionId), 'codex-home')
}

/**
 * The human's REAL `auth.json`, which an interactive session borrows (decision
 * 5). Asked of the doctor's own probe so the launcher and the "Codex login"
 * check can never disagree about where credentials live; `authFile` is optional
 * on the shared spec type (Claude Code has none on darwin), so the same default
 * it uses stands in.
 */
function realCodexAuthFile(env: NodeJS.ProcessEnv = process.env): string {
  return CODEX.authFile?.(env) ?? join(homedir(), '.codex', 'auth.json')
}

// --- config.toml ------------------------------------------------------------

/**
 * A TOML basic string. JSON's escaping rules are TOML's, which matters most for
 * Windows: a bare `C:\wt\feature` in a basic string reads `\w` as an invalid
 * escape and the whole config fails to parse.
 */
function toml(value: string): string {
  return JSON.stringify(value)
}

interface CodexConfigInput {
  session: SessionRow
  config: RuncastleConfig
  /** The model resolved for this session's step — never the CLI's own default. */
  model: string
  /** The session's working directory, trusted so Codex never asks at startup. */
  worktreePath: string
  /** `[mcp_servers.*]` tables lifted from the human's own config (`sessionMcp: 'inherit'`). */
  inheritedMcpServers?: string
}

/**
 * `$CODEX_HOME/config.toml` — everything the Claude adapter passes as flags.
 *
 * - `sandbox_mode = "workspace-write"` with `approval_policy = "never"` is the
 *   `--permission-mode acceptEdits` analogue (pinned against the live CLI's
 *   `SandboxMode`/`AskForApproval` wire values): the agent writes inside its
 *   worktree without stopping to ask, and the sandbox still applies.
 * - `[projects."<worktree>"] trust_level = "trusted"` answers the first-run
 *   "do you trust this folder?" prompt before it can block the session — a
 *   dialog fires BEFORE the SessionStart hook, so it would strand the terminal
 *   with no `live` row and no kickoff.
 * - `[mcp_servers.runcastle]` is the same Streamable-HTTP server every Claude
 *   session gets, with session identity on the same `X-Runcastle-Session`
 *   header (`http_headers` is Codex's spelling of Claude's `headers`).
 */
function renderCodexConfig(input: CodexConfigInput): string {
  const { session, config, model, worktreePath, inheritedMcpServers } = input
  return [
    `# Generated by runcastle for session ${session.id} — rewritten at every launch.`,
    `model = ${toml(model)}`,
    'sandbox_mode = "workspace-write"',
    'approval_policy = "never"',
    '',
    `[projects.${toml(worktreePath)}]`,
    'trust_level = "trusted"',
    '',
    // The human's own servers come FIRST: TOML wants a parent table declared
    // before its sub-tables, and `[mcp_servers]` is one of the shapes a hand
    // written config uses.
    ...(inheritedMcpServers ? [inheritedMcpServers, ''] : []),
    '[mcp_servers.runcastle]',
    `url = ${toml(`${serverUrlFor(config)}/mcp`)}`,
    `http_headers = { "X-Runcastle-Session" = ${toml(session.id)} }`,
    '',
  ].join('\n')
}

/**
 * The `[mcp_servers…]` tables of the human's own `config.toml`, for
 * `sessionMcp: 'inherit'` — a Codex session keeps the servers it would have had
 * outside runcastle, exactly as a Claude session does without
 * `--strict-mcp-config`.
 *
 * Lifted as TEXT rather than parsed and re-emitted: a server entry can carry
 * anything from a command line to OAuth settings, and copying the lines through
 * verbatim cannot lose a field we did not think to model. Our own entry is
 * dropped if the human happens to have one, so the generated table always wins.
 */
export function mcpServerTables(userConfigToml: string): string {
  const sections: string[] = []
  let keep = false
  for (const line of userConfigToml.split(/\r?\n/)) {
    const header = /^\s*\[\[?([^\]]+)\]\]?/.exec(line)
    if (header) {
      const path = header[1].trim()
      keep = path === 'mcp_servers' || path.startsWith('mcp_servers.')
      if (keep && /^mcp_servers\.["']?runcastle["']?$/.test(path)) keep = false
    }
    if (keep) sections.push(line)
  }
  return sections.join('\n').trim()
}

/** The `[mcp_servers…]` tables of the human's real Codex home, when it has any. */
function readInheritedMcpServers(env: NodeJS.ProcessEnv = process.env): string {
  const path = join(dirname(realCodexAuthFile(env)), 'config.toml')
  if (!existsSync(path)) return ''
  try {
    return mcpServerTables(readFileSync(path, 'utf8'))
  } catch {
    // A config we cannot read is not a launch we should refuse — the session
    // still gets runcastle's own server, which is the one it needs.
    return ''
  }
}

// --- hooks.json -------------------------------------------------------------

interface CodexCommandHook {
  type: 'command'
  command: string
  /** The win32 spelling; Codex prefers it over `command` there. */
  commandWindows?: string
}

interface CodexMatcherGroup {
  /** A regex matched against the tool name. Omitted = every call of the event. */
  matcher?: string
  hooks: CodexCommandHook[]
}

export interface CodexHooksFile {
  hooks: {
    SessionStart: CodexMatcherGroup[]
    UserPromptSubmit: CodexMatcherGroup[]
    Stop: CodexMatcherGroup[]
    SessionEnd: CodexMatcherGroup[]
    /** The talk-session edit guard; absent for the one kind that may write code. */
    PreToolUse?: CodexMatcherGroup[]
  }
}

/**
 * `$CODEX_HOME/hooks.json` — the same five lifecycle events as `renderSettings`,
 * invoking the same hook client. `hook-client.ts` is runtime-neutral (stdin JSON
 * → `POST /api/hooks/<event>`), so the whole server side of the lifecycle —
 * `launching → live` on SessionStart, `awaiting-input` on Stop, `ended` on
 * SessionEnd, the kickoff delivery receipt on UserPromptSubmit, and the edit
 * guard's deny verdict on PreToolUse — works with nothing changed.
 *
 * Two deliberate differences from the Claude settings. `SessionStart` takes no
 * per-source matcher: Claude Code needs one entry per source, and Codex's
 * matcher is a tool-name regex, so a matcher here would be a filter that never
 * matches. And no `timeout` is declared — Codex's per-event defaults apply
 * rather than a field whose unit we have not pinned against the live CLI.
 *
 * `commandWindows` carries the same invocation on win32; the hook client is a
 * `bun run` of a path this process computed with `node:path`, so the two
 * spellings agree, but Codex takes the platform-specific field when it is there
 * and the launch should not depend on which one it happens to prefer.
 */
export function renderCodexHooks(
  hookClient: string,
  kind?: SessionKind,
  platform: NodeJS.Platform = process.platform,
): CodexHooksFile {
  const cmd = (event: string): CodexCommandHook => {
    const command = `bun run "${hookClient}" ${event}`
    return platform === 'win32'
      ? { type: 'command', command, commandWindows: command }
      : { type: 'command', command }
  }
  return {
    hooks: {
      SessionStart: [{ hooks: [cmd('session-start')] }],
      UserPromptSubmit: [{ hooks: [cmd('user-prompt')] }],
      Stop: [{ hooks: [cmd('stop')] }],
      SessionEnd: [{ hooks: [cmd('session-end')] }],
      ...(kind === undefined || guardsEdits(kind)
        ? { PreToolUse: [{ matcher: EDIT_TOOL_MATCHER, hooks: [cmd('pre-tool')] }] }
        : {}),
    },
  }
}

// --- skills -----------------------------------------------------------------

/** Where Codex discovers skills, relative to the session's working directory. */
const CODEX_SKILLS_REL = join('.agents', 'skills')

/** The ignore entry that keeps the rendered pack out of the human's diff. */
const CODEX_SKILLS_IGNORE = '.agents/'

/**
 * Render the runcastle skill pack into the session's worktree in Codex's format
 * (`.agents/skills/<name>/SKILL.md`, discovered from the working directory up).
 *
 * One content source, two rendered formats: the pack's frontmatter is already
 * `name`/`description`, which is exactly what Codex reads, so this is a copy
 * rather than a translation — the day a skill's prose changes, both runtimes get
 * it.
 *
 * The worktree is a real checkout of the feature branch, so the rendered files
 * must never become part of the human's diff. They are excluded through
 * `.git/info/exclude` — the repo's own `.gitignore` is the human's file and
 * belongs to their PR, and runcastle writing to it would be a change they never
 * asked for.
 *
 * Best-effort throughout: a worktree that is not on disk (the `spawn:false`
 * smoke path computes one without creating it) renders nothing and returns
 * nothing, rather than making a directory out of a path nobody checked out.
 */
function writeCodexSkills(worktreePath: string, packDir: string): string[] {
  if (!existsSync(worktreePath)) return []
  const source = join(packDir, 'skills')
  if (!existsSync(source)) return []

  const written: string[] = []
  for (const name of readdirSync(source)) {
    const skill = join(source, name, 'SKILL.md')
    if (!existsSync(skill)) continue
    const target = join(worktreePath, CODEX_SKILLS_REL, name)
    mkdirSync(target, { recursive: true })
    const path = join(target, 'SKILL.md')
    copyFileSync(skill, path)
    written.push(path)
  }
  if (written.length > 0) excludeFromGit(worktreePath, CODEX_SKILLS_IGNORE)
  return written
}

/**
 * Add `entry` to this checkout's `.git/info/exclude`, once. Linked worktrees
 * keep `info/` in the repository's COMMON git dir (their own `.git` is a file
 * naming `…/.git/worktrees/<name>`), which is where git reads the file from —
 * so resolving it is not the same as joining `.git/info` to the worktree.
 */
function excludeFromGit(worktreePath: string, entry: string): void {
  try {
    const info = gitInfoDir(worktreePath)
    if (!info) return
    mkdirSync(info, { recursive: true })
    const path = join(info, 'exclude')
    const existing = existsSync(path) ? readFileSync(path, 'utf8') : ''
    if (existing.split(/\r?\n/).some((line) => line.trim() === entry)) return
    const head = existing.length > 0 && !existing.endsWith('\n') ? `${existing}\n` : existing
    writeFileSync(path, `${head}${entry}\n`, 'utf8')
  } catch {
    // An unwritable git dir costs the human a dirty-tree entry, not a session.
  }
}

/** The `info/` dir git reads `exclude` from for this checkout, or null. */
function gitInfoDir(worktreePath: string): string | null {
  const dotGit = join(worktreePath, '.git')
  if (!existsSync(dotGit)) return null
  if (statSync(dotGit).isDirectory()) return join(dotGit, 'info')

  const named = /^gitdir:\s*(.+)$/m.exec(readFileSync(dotGit, 'utf8'))
  if (!named) return null
  const gitDir = resolve(worktreePath, named[1].trim())
  // `<common>/worktrees/<name>` → `<common>`; anything else IS the git dir.
  const parent = dirname(gitDir)
  return basename(parent) === 'worktrees' ? join(dirname(parent), 'info') : join(gitDir, 'info')
}

// --- argv -------------------------------------------------------------------

/**
 * The `codex` argv AFTER the program name. Everything else about the launch is
 * in `CODEX_HOME`, so this is only the two things a file cannot say.
 *
 * `resume <id>` reopens the conversation the SessionStart hook recorded as
 * `ccSessionId`, which is how reopening a terminal after runcastle restarts
 * continues it rather than starting cold from the docs.
 * `--dangerously-bypass-hook-trust` is required because we AUTHOR the hooks: a
 * freshly-generated `hooks.json` has no persisted trust, and without the flag
 * every lifecycle event is silently skipped — no `live` row, no kickoff, no
 * edit guard.
 */
function buildCodexArgs(input: { resumeSessionId?: string }): string[] {
  return [
    ...(input.resumeSessionId ? ['resume', input.resumeSessionId] : []),
    '--dangerously-bypass-hook-trust',
  ]
}

/**
 * The kickoff lines a Codex session is opened with — the shared per-kind table
 * (see {@link kickoffLinesFor}), spelled `$skill` because that is how Codex
 * invokes a skill it discovered under `.agents/skills`.
 */
export const KICKOFF_LINES: Record<SessionKind, string> = kickoffLinesFor('codex')

export const codexRuntime: AgentRuntimeAdapter = {
  id: 'codex',
  binary: CODEX_BIN,

  /**
   * `RUNCASTLE_CODEX_BIN` overrides; otherwise PATH is scanned for `codex` with
   * Windows extensions, then the well-known install dirs. Falls back to the bare
   * name so the spawn can make a final attempt.
   */
  resolveBinary(): string {
    return resolveTool(CODEX_BIN)
  },

  /**
   * Ready when the CLI is visible AND the human has logged in. The second half
   * is what makes this different from the Claude adapter: a Codex session runs
   * on a copy of the human's own `auth.json` (decision 5), so a missing one is
   * not a session that logs in — it is a synthetic home with no credentials at
   * all, which fails inside a terminal that closes as fast as it opened.
   */
  checkReady(): RuntimeReadiness {
    if (this.resolveBinary() === CODEX_BIN) {
      return {
        ok: false,
        reason:
          'the Codex CLI (`codex`) is not on the PATH this runcastle server inherited, nor in ' +
          'the usual install locations',
        doctorHint:
          'Run `runcastle doctor` and fix its "Codex CLI" probe, then restart runcastle from a ' +
          'terminal where `codex --version` works.',
      }
    }
    if (!existsSync(realCodexAuthFile())) {
      return {
        ok: false,
        reason:
          'Codex is installed but not logged in — runcastle copies your own credentials into ' +
          `each session's home, and there are none at ${realCodexAuthFile()}`,
        doctorHint: `Run \`${CODEX.loginCommand}\` (the wizard and Settings can run it for you), then relaunch.`,
      }
    }
    return { ok: true }
  },

  async writeArtifacts(input: RuntimeLaunchInput): Promise<RuntimeLaunchSpec> {
    const home = codexHomeDir(input.session.id)
    mkdirSync(home, { recursive: true })

    const configPath = join(home, 'config.toml')
    const hooksPath = join(home, 'hooks.json')
    const agentsPath = join(home, 'AGENTS.md')

    writeFileSync(
      configPath,
      renderCodexConfig({
        session: input.session,
        config: input.config,
        model: input.model,
        worktreePath: input.worktreePath,
        // 'runcastleOnly' is isolation by construction — a synthetic home the
        // human's servers were never written into.
        ...(input.config.sessionMcp === 'inherit'
          ? { inheritedMcpServers: readInheritedMcpServers() }
          : {}),
      }),
      'utf8',
    )
    writeFileSync(
      hooksPath,
      JSON.stringify(renderCodexHooks(hookClientPath(), input.session.kind), null, 2),
      'utf8',
    )
    // The adapter names the runtime the briefing is rendered for, so the prompt's
    // skill spelling can never disagree with the CLI that is about to read it.
    writeFileSync(agentsPath, renderSessionPrompt({ ...input, runtime: this.id }), 'utf8')

    const files = [configPath, hooksPath, agentsPath]

    // Auth is borrowed, not managed: `checkReady` already refused a launch with
    // no credentials, and the smoke path (which skips it) simply gets a home
    // without them.
    const auth = realCodexAuthFile()
    if (existsSync(auth)) {
      const copied = join(home, 'auth.json')
      copyFileSync(auth, copied)
      files.push(copied)
    }

    files.push(...writeCodexSkills(input.worktreePath, resolvePluginDir()))

    return {
      files,
      argv: buildCodexArgs({
        ...(input.resumeSessionId ? { resumeSessionId: input.resumeSessionId } : {}),
      }),
      env: {
        CODEX_HOME: home,
        RUNCASTLE_SESSION_ID: input.session.id,
        RUNCASTLE_SERVER_URL: input.serverUrl,
      },
      envScrub: [],
    }
  },

  kickoffLine(kind: SessionKind): string {
    return KICKOFF_LINES[kind]
  },
}
